### ISSUE TITLE
Failed to convert opus to wav

### ISSUE THREAD

**Issue by mct10** [SpeechColab/GigaSpeech#102]
Hi. 
I'm trying to use <code>utils/opus_to_wav.py</code> to convert an opus file to wav file. 
However, I ran the comman <code>python utils/opus_to_wav.py ~/AUD0000001400.opus</code>, and the program generates the following error:
```
Traceback (most recent call last):
  File "utils/opus_to_wav.py", line 40, in <module>
    main()
  File "utils/opus_to_wav.py", line 36, in main
    convert_opus2wav(args.opus_scp, args.remove_opus)
  File "utils/opus_to_wav.py", line 21, in convert_opus2wav
    for line in oscp:
  File "xxx/miniconda3/envs/translation/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcd in position 14: invalid continuation byte
```
I have also tried gbk, but the result is the same:

```
Traceback (most recent call last):
  File "utils/opus_to_wav.py", line 40, in <module>
    main()
  File "utils/opus_to_wav.py", line 36, in main
    convert_opus2wav(args.opus_scp, args.remove_opus)
  File "utils/opus_to_wav.py", line 21, in convert_opus2wav
    for line in oscp:
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa2 in position 22: illegal multibyte sequence
```

Could you please help me with this issue? Thank you.

**Comment by dophist** [comment]
try:
```
util/opus_to_wav.py  xxx.scp
```
where xxx.scp contains a line:
```
AUD0000001400    ~/AUD0000001400.opus
```

**Comment by mct10** [comment]
Now I understand how <code>util/opus_to_wav.py</code> works. Thanks a lot!

**Comment by ayushP-uwc** [comment]
Hi, where is the SCP scirpt?
