### ISSUE TITLE
Unable to download `large` split

### ISSUE THREAD

**Issue by sanchit-gandhi** [SpeechColab/GigaSpeech#112]
When trying downloading the `large` split, I often encounter one of two errors:
<details>
<summary> A protocol error (click to expand) </summary>

```
Downloading from https://freedata.oss-cn-beijing.aliyuncs.com/magichub/GigaSpeech/audio/youtube/P0013.tgz.aes                                                      
1.02GB [02:59, 6.12MB/s]                                                                                                                                           
Successfully verified md5 for /home/sanchitgandhi/cache/huggingface/datasets/audio/youtube/P0013.tgz.aes                                                           
Downloading from https://freedata.oss-cn-beijing.aliyuncs.com/magichub/GigaSpeech/audio/youtube/P0014.tgz.aes                                                      
Traceback (most recent call last):                                                                                                                                 
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open                                                                                               
    h.request(req.get_method(), req.selector, req.data, headers,                                                                                                   
  File "/usr/lib/python3.8/http/client.py", line 1256, in request                                                                                                  
    self._send_request(method, url, body, headers, encode_chunked)                                                                                                 
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request                                                                                            
    self.endheaders(body, encode_chunked=encode_chunked)                                                                                                           
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders                                                                                               
    self._send_output(message_body, encode_chunked=encode_chunked)                                                                                                 
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output                                                                                             
    self.send(msg)                                                                                                                                                 
  File "/usr/lib/python3.8/http/client.py", line 951, in send                                                                                                      
    self.connect()                                                                                                      
  File "/usr/lib/python3.8/http/client.py", line 1425, in connect                                                       
    self.sock = self._context.wrap_socket(self.sock,                                                                      
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket                                                            
    return self.sslsocket_class._create(                                                                                  
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create                                                               
    self.do_handshake()                                                                                                       
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake                                                                    
    self._sslobj.do_handshake()                                                                                               
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:1131) 

During handling of the above exception, another exception occurred:                                                     
                                                                                                                                         
Traceback (most recent call last):                                                                                                                 
  File "download_gigaspeech.py", line 31, in <module>                                                                                            
    gigaspeech.download(password=password, subset=f"{{{args.subset.upper()}}}", host=args.host)                                                    
  File "/home/sanchitgandhi/hf/lib/python3.8/site-packages/speechcolab/datasets/gigaspeech.py", line 101, in download                                   
    prepare_objects_from_release(audio_source)                                                                                                       
  File "/home/sanchitgandhi/hf/lib/python3.8/site-packages/speechcolab/datasets/gigaspeech.py", line 87, in prepare_objects_from_release                
    self.download_and_process_object_from_release(aes_list[category][path], path)                                                                         
  File "/home/sanchitgandhi/hf/lib/python3.8/site-packages/speechcolab/datasets/gigaspeech.py", line 124, in download_and_process_object_from_release       
    download(local_obj, remote_obj, show_progress_bar=True)                                                                                                    
  File "/home/sanchitgandhi/hf/lib/python3.8/site-packages/speechcolab/utils/download.py", line 44, in download                                         
    return download_from_http(local_filename, url, show_progress_bar)                                                             
  File "/home/sanchitgandhi/hf/lib/python3.8/site-packages/speechcolab/utils/download.py", line 10, in download_from_http                                   
    response = urlopen(url)                                                                                                       
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen                                                     
    return opener.open(url, data, timeout)                                                                                        
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open                                                              
    response = self._open(req, data)                                                                                              
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open                                                                                  
    result = self._call_chain(self.handle_open, protocol, protocol +                                                                     
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain                                                                            
    result = func(*args)                                                                                                                       
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open                                                                            
    return self.do_open(http.client.HTTPSConnection, req,                                                                                            
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open                                                                                    
    raise URLError(err)                                                                                                                                   
urllib.error.URLError: <urlopen error EOF occurred in violation of protocol (_ssl.c:1131)> 
```
</details>

<details>
<summary>The download hanging and not going to completion (click to expand) </summary>

```
GigaSpeech downloading will start in 5 seconds
5
4
3
2
1
Start to download files.yaml
Start to download GigaSpeech metadata
Skipping /home/sanchitgandhi/cache/huggingface/datasets/gigaspeech/GigaSpeech.json.gz.aes, successfully retrieved already.
Downloading from https://freedata.oss-cn-beijing.aliyuncs.com/magichub/GigaSpeech/audio/youtube/P0001.tgz.aes

  0%|          | 0.00/1.01G [00:00<?, ?B/s]
  0%|          | 12.0k/1.01G [00:00<5:04:27, 59.6kB/s]
  0%|          | 40.0k/1.01G [00:00<2:51:00, 106kB/s]
  0%|          | 92.0k/1.01G [00:00<1:43:34, 175kB/s]
  0%|          | 180k/1.01G [00:00<1:05:15, 278kB/s]
  0%|          | 308k/1.01G [00:01<44:39, 406kB/s]
  0%|          | 628k/1.01G [00:01<22:28, 807kB/s]
  0%|          | 1.19M/1.01G [00:01<12:07, 1.50MB/s]
  0%|          | 2.38M/1.01G [00:01<06:08, 2.95MB/s]
  0%|          | 4.79M/1.01G [00:01<03:05, 5.83MB/s]
  1%|          | 7.50M/1.01G [00:02<02:01, 8.87MB/s]
  1%|          | 9.80M/1.01G [00:02<01:32, 11.7MB/s]
  1%|          | 11.1M/1.01G [00:02<01:46, 10.1MB/s]
  1%|          | 12.7M/1.01G [00:02<01:38, 10.9MB/s]
  1%|▏         | 14.0M/1.01G [00:02<01:38, 10.9MB/s]
  1%|▏         | 15.5M/1.01G [00:02<01:29, 12.0MB/s]
  2%|▏         | 16.7M/1.01G [00:02<01:29, 12.0MB/s]
  2%|▏         | 18.0M/1.01G [00:02<01:32, 11.6MB/s]
  2%|▏         | 19.2M/1.01G [00:03<02:14, 7.95MB/s]
  2%|▏         | 21.9M/1.01G [00:03<01:47, 9.94MB/s]
  2%|▏         | 24.5M/1.01G [00:03<01:22, 12.9MB/s]
  2%|▏         | 25.9M/1.01G [00:03<01:24, 12.5MB/s]
  3%|▎         | 27.3M/1.01G [00:03<01:30, 11.7MB/s]
  3%|▎         | 28.6M/1.01G [00:03<01:34, 11.2MB/s]
  3%|▎         | 30.0M/1.01G [00:04<01:29, 11.9MB/s]
  3%|▎         | 31.5M/1.01G [00:04<01:23, 12.7MB/s]
  3%|▎         | 32.7M/1.01G [00:04<01:23, 12.6MB/s]
  3%|▎         | 34.2M/1.01G [00:04<01:19, 13.3MB/s]
  3%|▎         | 35.5M/1.01G [00:04<01:19, 13.2MB/s]
  4%|▎         | 37.1M/1.01G [00:04<01:14, 14.0MB/s]
  4%|▎         | 38.4M/1.01G [00:04<01:16, 13.7MB/s]
  4%|▍         | 39.7M/1.01G [00:04<01:25, 12.3MB/s]
  4%|▍         | 41.0M/1.01G [00:04<01:27, 12.0MB/s]
  4%|▍         | 42.7M/1.01G [00:05<01:24, 12.4MB/s]
  4%|▍         | 44.4M/1.01G [00:05<01:16, 13.6MB/s]
  4%|▍         | 45.7M/1.01G [00:05<01:23, 12.5MB/s]
  5%|▍         | 47.6M/1.01G [00:05<01:15, 13.7MB/s]
  5%|▍         | 48.9M/1.01G [00:05<01:20, 12.9MB/s]
  5%|▍         | 50.9M/1.01G [00:05<01:11, 14.4MB/s]
  5%|▌         | 52.3M/1.01G [00:05<01:14, 13.9MB/s]
  5%|▌         | 53.8M/1.01G [00:05<01:12, 14.2MB/s]
  5%|▌         | 55.2M/1.01G [00:05<01:14, 13.8MB/s]
  5%|▌         | 56.5M/1.01G [00:06<01:55, 8.92MB/s]
  6%|▌         | 59.4M/1.01G [00:06<01:34, 10.9MB/s]
  6%|▌         | 62.3M/1.01G [00:06<01:24, 12.1MB/s]
  6%|▋         | 64.9M/1.01G [00:06<01:22, 12.3MB/s]
  6%|▋         | 67.2M/1.01G [00:07<01:14, 13.7MB/s]
  7%|▋         | 68.6M/1.01G [00:07<01:20, 12.6MB/s]
  7%|▋         | 70.8M/1.01G [00:07<01:14, 13.7MB/s]
  7%|▋         | 72.3M/1.01G [00:07<01:14, 13.5MB/s]
  7%|▋         | 73.8M/1.01G [00:07<01:15, 13.4MB/s]
  7%|▋         | 76.0M/1.01G [00:07<01:04, 15.6MB/s]
  7%|▋         | 77.5M/1.01G [00:07<01:13, 13.8MB/s]
  8%|▊         | 79.1M/1.01G [00:07<01:13, 13.8MB/s]
  8%|▊         | 80.5M/1.01G [00:08<01:11, 14.0MB/s]
  8%|▊         | 81.9M/1.01G [00:08<01:24, 11.8MB/s]
  8%|▊         | 83.8M/1.01G [00:08<01:25, 11.7MB/s]
  8%|▊         | 85.5M/1.01G [00:08<01:18, 12.7MB/s]
  8%|▊         | 86.8M/1.01G [00:08<01:17, 12.9MB/s]
  8%|▊         | 88.2M/1.01G [00:08<01:21, 12.2MB/s]
  9%|▊         | 89.6M/1.01G [00:08<01:19, 12.6MB/s]
  9%|▊         | 90.8M/1.01G [00:08<01:19, 12.5MB/s]
  9%|▉         | 92.5M/1.01G [00:09<01:11, 13.8MB/s]
  9%|▉         | 93.8M/1.01G [00:09<01:17, 12.9MB/s]
  9%|▉         | 95.4M/1.01G [00:09<01:14, 13.3MB/s]
  9%|▉         | 96.7M/1.01G [00:09<01:18, 12.6MB/s]
  9%|▉         | 98.4M/1.01G [00:09<01:11, 13.8MB/s]
 10%|▉         | 99.7M/1.01G [00:09<01:16, 12.8MB/s]
 10%|▉         | 101M/1.01G [00:09<01:39, 9.92MB/s]
 10%|▉         | 103M/1.01G [00:10<01:43, 9.50MB/s]
 10%|█         | 105M/1.01G [00:10<01:39, 9.85MB/s]
 10%|█         | 107M/1.01G [00:10<01:36, 10.1MB/s]
 10%|█         | 109M/1.01G [00:10<01:34, 10.3MB/s]
 11%|█         | 111M/1.01G [00:10<01:32, 10.5MB/s]
 11%|█         | 113M/1.01G [00:11<01:31, 10.6MB/s]
 11%|█         | 115M/1.01G [00:11<01:29, 10.8MB/s]
 11%|█▏        | 118M/1.01G [00:11<01:28, 10.9MB/s]
 12%|█▏        | 120M/1.01G [00:11<01:27, 11.0MB/s]
 12%|█▏        | 122M/1.01G [00:11<01:13, 13.0MB/s]
 12%|█▏        | 123M/1.01G [00:11<01:14, 13.0MB/s]
 12%|█▏        | 125M/1.01G [00:12<01:27, 10.9MB/s]
 12%|█▏        | 126M/1.01G [00:12<01:46, 9.02MB/s]
 12%|█▏        | 128M/1.01G [00:12<01:56, 8.21MB/s]
 12%|█▏        | 129M/1.01G [00:12<01:58, 8.07MB/s]
 13%|█▎        | 130M/1.01G [00:12<01:46, 8.94MB/s]
 13%|█▎        | 131M/1.01G [00:13<01:51, 8.52MB/s]
 13%|█▎        | 132M/1.01G [00:13<02:07, 7.43MB/s]
 13%|█▎        | 133M/1.01G [00:13<01:44, 9.05MB/s]
 13%|█▎        | 134M/1.01G [00:13<01:49, 8.66MB/s]
 13%|█▎        | 135M/1.01G [00:13<02:06, 7.47MB/s]
 13%|█▎        | 137M/1.01G [00:13<01:41, 9.28MB/s]
 13%|█▎        | 138M/1.01G [00:13<01:46, 8.83MB/s]
 13%|█▎        | 139M/1.01G [00:14<02:03, 7.62MB/s]
 14%|█▎        | 140M/1.01G [00:14<01:37, 9.63MB/s]
 14%|█▎        | 141M/1.01G [00:14<01:43, 9.06MB/s]
 14%|█▎        | 142M/1.01G [00:14<01:59, 7.84MB/s]
 14%|█▍        | 144M/1.01G [00:14<01:38, 9.53MB/s]
 14%|█▍        | 145M/1.01G [00:14<01:41, 9.19MB/s]
 14%|█▍        | 146M/1.01G [00:14<01:58, 7.89MB/s]
 14%|█▍        | 147M/1.01G [00:14<01:35, 9.80MB/s]
 14%|█▍        | 148M/1.01G [00:15<01:39, 9.43MB/s]
 14%|█▍        | 149M/1.01G [00:15<01:55, 8.09MB/s]
 15%|█▍        | 151M/1.01G [00:15<01:34, 9.88MB/s]
 15%|█▍        | 152M/1.01G [00:15<01:36, 9.60MB/s]
 15%|█▍        | 153M/1.01G [00:15<01:53, 8.21MB/s]
 15%|█▍        | 155M/1.01G [00:15<01:31, 10.1MB/s]
 15%|█▌        | 156M/1.01G [00:15<01:34, 9.76MB/s]
 15%|█▌        | 157M/1.01G [00:16<01:50, 8.36MB/s]
 15%|█▌        | 159M/1.01G [00:16<01:30, 10.2MB/s]
 15%|█▌        | 160M/1.01G [00:16<01:33, 9.87MB/s]
 15%|█▌        | 161M/1.01G [00:16<01:49, 8.44MB/s]
 16%|█▌        | 162M/1.01G [00:16<01:28, 10.3MB/s]
 16%|█▌        | 163M/1.01G [00:16<01:32, 9.98MB/s]
 16%|█▌        | 164M/1.01G [00:16<01:47, 8.54MB/s]
 16%|█▌        | 166M/1.01G [00:17<01:26, 10.6MB/s]
 16%|█▌        | 167M/1.01G [00:17<01:30, 10.1MB/s]
 16%|█▌        | 168M/1.01G [00:17<01:45, 8.65MB/s]
 16%|█▋        | 170M/1.01G [00:17<01:26, 10.5MB/s]
 16%|█▋        | 171M/1.01G [00:17<01:31, 9.90MB/s]
 17%|█▋        | 172M/1.01G [00:17<01:45, 8.64MB/s]
 17%|█▋        | 174M/1.01G [00:17<01:25, 10.6MB/s]
 17%|█▋        | 175M/1.01G [00:17<01:30, 10.0MB/s]
 17%|█▋        | 176M/1.01G [00:18<01:43, 8.70MB/s]
 17%|█▋        | 177M/1.01G [00:18<02:05, 7.18MB/s]
 17%|█▋        | 180M/1.01G [00:18<01:32, 9.79MB/s]
 17%|█▋        | 181M/1.01G [00:18<01:28, 10.1MB/s]
 18%|█▊        | 182M/1.01G [00:18<01:39, 8.99MB/s]
 18%|█▊        | 183M/1.01G [00:19<01:47, 8.37MB/s]
 18%|█▊        | 184M/1.01G [00:19<02:02, 7.31MB/s]
 18%|█▊        | 185M/1.01G [00:19<01:48, 8.24MB/s]
 18%|█▊        | 186M/1.01G [00:19<02:04, 7.21MB/s]
 18%|█▊        | 187M/1.01G [00:19<02:06, 7.04MB/s]
 18%|█▊        | 188M/1.01G [00:19<01:47, 8.31MB/s]
 18%|█▊        | 189M/1.01G [00:19<02:05, 7.08MB/s]
 18%|█▊        | 190M/1.01G [00:20<02:08, 6.92MB/s]
 18%|█▊        | 191M/1.01G [00:20<01:4
```
</details>

Is there any recommended advice for downloading the `large` data split? I have tried downloading this split on numerous occasions, but the download almost always hangs!

Many thanks!

**Comment by dophist** [comment]
There is nothing specific to M subset, all subsets are organized the same way.  The second error seems to be unstable connection of your local network. For the first one, it's outside the scope of our downloading tool, maybe upgrade your python request package? I'm not sure.

**Comment by sanchit-gandhi** [comment]
Hey @dophist, thanks for getting back to me! I've established that my local network isn't the issue: I've been attempting to download the dataset using gcloud machines, where my SSH tunnel remains running but the download consistently hangs (the same behaviour that @patrickvonplaten has outlined). I've been using a fresh python env with the latest version of speechcolab, so I don't think that's the issue at play. 

Big +1 on making the download easier! I've tried in the region of 5-6 times now to download the dataset, and I keep running into the either the protocol error or (the more common) hanging issue.

**Comment by dophist** [comment]
> Thanks for the answer @dophist!
> 
> I must confess that for me it's also very difficult to download the whole dataset. I've tried the script on GCP machines and local machines in different locations (US, Europe) and the scrcipt always hangs eventually.
> 
> Do you think there could be a way to make the download easier? E.g. maybe providing access through the Hugging Face Hub? cc @chenguoguo :-)

Patrick, I think it is great that HuggingFace is willing to setup a mirror for GigaSpeech distributions, I fully second that. Guoguo is running several startups so he might be quite busy to respond, you can ping him with specific info on how we can help to make this happen, I'll message him as well : )

**Comment by patrickvonplaten** [comment]
This sounds great! Just sent you a mail with more info :-)
