### ISSUE TITLE
zlib.error: Error -3 while decompressing data: incorrect header check

### ISSUE THREAD

**Issue by ddlBoJack** [SpeechColab/GigaSpeech#93]
Hi, I have a bug when decompressing the file `GigaSpeech.json.gz`:

```bash
GigaSpeech downloading will start in 5 seconds
5
4
3
2
1
Start to download files.yaml
Start to download GigaSpeech metadata
Skipping /home/share/maziyang/gigaspeech/GigaSpeech.json.gz.aes, successfully retrieved already.
Traceback (most recent call last):
  File "<stdin>", line 3, in <module>
  File "/home/maziyang/anaconda3/envs/espnet/lib/python3.8/site-packages/speechcolab/datasets/gigaspeech.py", line 91, in download
    prepare_objects_from_release('metadata')
  File "/home/maziyang/anaconda3/envs/espnet/lib/python3.8/site-packages/speechcolab/datasets/gigaspeech.py", line 87, in prepare_objects_from_release
    self.download_and_process_object_from_release(aes_list[category][path], path)
  File "/home/maziyang/anaconda3/envs/espnet/lib/python3.8/site-packages/speechcolab/datasets/gigaspeech.py", line 167, in download_and_process_object_from_release
    f_out.write(z.decompress(chunk))
zlib.error: Error -3 while decompressing data: incorrect header check
```

I really need your help.

**Comment by ddlBoJack** [comment]
Thanks @jimbozhang for fixing the bug. 
We can close the issue.
